services:
  # A Docker web service
- type: web
  name: Hackwomen-Team-5-Back
  env: docker
  autoDeploy: false
  plan: free 
  region: oregon 
  envVars:
      - key: ENV
        sync: false
      - key: DJANGO_ALLOWED_HOSTS
        sync: false
      - key: CORS_ALLOW_ALL_ORIGINS
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
      - key: DEBUG
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
 
