# Generated by Django 4.1.7 on 2023-04-18 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comments',
            table=None,
        ),
    ]
